server:
    port: 8082

spring:
    application:
        name: multitenancy

springdoc:
    swagger-ui:
        oauth:
            client-id: multitenancy-hom

jwt:
    auth:
        issuers:
            multitenancy-hom:
                resource-id: multitenancy-hom
                principal-attribute: principal_username
                tenant-id: "tenanatId"