server:
    port: 8082

spring:
    application:
        name: multitenancy
#    security:
#        oauth2:
#            resourceserver:
#                jwt:
#                    issuer-uri: http://localhost:8080/realms/multitenancy
#                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#springdoc:
#    swagger-ui:
#        oauth:
#            client-id: multitenancy-hom
#

jwt:
    auth:
        issuers:
            multitenancy-hom:
                resource-id: multitenancy-hom
                principal-attribute: principal_username
                tenant-id: "tenanatId"

